using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using FreelancerCopilot.API.Models;

namespace FreelancerCopilot.API.Services
{
    public class AiProposalService
    {
        private readonly IConfiguration _config;
        private readonly HttpClient _httpClient;

        public AiProposalService(HttpClient httpClient, IConfiguration config)
        {
            _httpClient = httpClient;
            _config = config;
        }

        public async Task<string> GenerateProposal(Job job)
        {
            var apiKey = _config["OpenAI:ApiKey"];
            var model = _config["OpenAI:Model"];

            if (string.IsNullOrWhiteSpace(apiKey))
                throw new Exception("OpenAI API key is missing.");

            var prompt = $@"
You are a top 1% freelance proposal writer.

Write a HIGH CONVERSION Upwork proposal.

Job Title: {job.Title}
Job Description: {job.Description}
Budget: {job.Budget}

Rules:
- Be short (150-200 words)
- Be persuasive but not spammy
- Focus on client pain points
- Mention ASP.NET Core + Angular experience
- End with a question to engage client
";

            var requestBody = new
            {
                model = model,
                messages = new[]
                {
                    new { role = "system", content = "You are a senior freelance proposal expert." },
                    new { role = "user", content = prompt }
                },
                temperature = 0.7
            };

            var request = new HttpRequestMessage(HttpMethod.Post, "https://api.openai.com/v1/chat/completions");

            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
            request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            request.Content = new StringContent(
                JsonSerializer.Serialize(requestBody),
                Encoding.UTF8,
                "application/json"
            );

            var response = await _httpClient.SendAsync(request);
            var responseJson = await response.Content.ReadAsStringAsync();

            // ❌ Handle HTTP errors
            if (!response.IsSuccessStatusCode)
            {
                throw new Exception($"OpenAI API failed ({response.StatusCode}): {responseJson}");
            }

            using var doc = JsonDocument.Parse(responseJson);
            var root = doc.RootElement;

            // ❌ Handle OpenAI error response
            if (root.TryGetProperty("error", out var error))
            {
                var errorMessage = error.GetProperty("message").GetString();
                throw new Exception($"OpenAI Error: {errorMessage}");
            }

            // ❌ Validate structure safely
            if (!root.TryGetProperty("choices", out var choices) ||
                choices.GetArrayLength() == 0)
            {
                throw new Exception($"Invalid OpenAI response format: {responseJson}");
            }

            var firstChoice = choices[0];

            if (!firstChoice.TryGetProperty("message", out var messageObj) ||
                !messageObj.TryGetProperty("content", out var content))
            {
                throw new Exception($"Missing message content in OpenAI response: {responseJson}");
            }

            var aiContent = content.GetString();

            return aiContent ?? "No content generated by AI.";
        }
    }
}